### ISSUE TITLE
Inconsistent dnsserver value update via netsh.exe

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/metabox#82] opened 2018-06-18 13:27 UTC
The following code for dnsserver update seems to be inconsistent across different hosts:

>  & netsh.exe interface ipv4 add dnsserver "$name" address=$dns index=1

https://github.com/SubPointSolutions/metabox/blob/origin/0.2.3-dev/src/metabox/lib/services/vagrant/vagrant_configs/scripts/metabox.vagrant.core/metabox.fix-second-network.ps1#L44

Sometimes it returns 1 without updating dnsserver value. Consequently, it fails host domain join.

We need to add more tracing for troubleshooting and ultimately re-write this in PoweShell. Currently builds are unstable across platforms. Additional trace such might be of help:
```
netsh interface ipv4 show interfaces
```

**Comment by SubPointSupport** [comment] 2018-06-19 17:00
Very much intermittent issues, a few times over a hundred builds so far.

**Comment by avishnyakov** [comment] 2018-07-08 14:30
Can't reproduce, we run several hundreds VMs  under CI. Closing for the time being.

**Closed by avishnyakov** 2018-07-08 14:30 UTC
Labels: enhancement
